name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '19'

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew help --no-configuration-cache
        shell: bash

      - run: ./gradlew help --no-configuration-cache
        shell: bash

      - run: ./gradlew help --configuration-cache
        shell: bash

      - run: ./gradlew help --configuration-cache
        if: always()
        shell: bash
